export enum ApplicationStatus {
  APPLIED = 'APPLIED',
  ASSESSMENT_IN_PROGRESS = 'ASSESSMENT_IN_PROGRESS',
  ASSESSMENT_COMPLETED = 'ASSESSMENT_COMPLETED',
  ELIGIBLE = 'ELIGIBLE',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  AGREEMENT_SIGNED = 'AGREEMENT_SIGNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
