export enum ProjectType {
  DATA_ENTRY = 'DATA_ENTRY',
  CONTENT_WRITING = 'CONTENT_WRITING',
  VIRTUAL_ASSISTANT = 'VIRTUAL_ASSISTANT',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  TRANSCRIPTION = 'TRANSCRIPTION',
  TRANSLATION = 'TRANSLATION',
  PROGRAMMING = 'PROGRAMMING',
  DESIGN = 'DESIGN',
  OTHER = 'OTHER',
}
